export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const MAINPAGE_ROUTE = '/'
export const PROFILE_ROUTE = '/studentProfile'
export const VACANCY_ROUTE = '/vacancy'